/**
 * Apple Wallet (.pkpass) integration — architecture placeholder.
 *
 * A real .pkpass is a signed zip archive (pass.json + images + manifest.json
 * + signature) built with:
 *   1. An Apple Developer "Pass Type ID" certificate + private key, created
 *      at developer.apple.com/account/resources/identifiers/list/passTypeId
 *   2. Apple's WWDR (Worldwide Developer Relations) intermediate certificate.
 *   3. Your Apple Developer Team Identifier.
 *
 * None of these can be generated by this app — they require an active,
 * paid Apple Developer Program membership and manual steps in Apple's
 * portal. Once available, set:
 *
 *   APPLE_PASS_TYPE_IDENTIFIER   e.g. "pass.com.passloyal.card"
 *   APPLE_TEAM_IDENTIFIER        e.g. "AB12CD34EF"
 *   APPLE_PASS_CERTIFICATE       base64-encoded Pass Type ID certificate (.pem)
 *   APPLE_PASS_CERTIFICATE_KEY   base64-encoded private key (.pem)
 *   APPLE_WWDR_CERTIFICATE       base64-encoded Apple WWDR certificate (.pem)
 *
 * Intended implementation: add the `passkit-generator` npm package, call it
 * from app/api/wallet/apple/[token]/route.ts to build a StoreCard pass with
 * the customer's points/level and a QR code encoding their wallet URL, sign
 * it, and return it with Content-Type: application/vnd.apple.pkpass.
 */

import type { PublicWalletCard } from "@/types/database";

export const APPLE_WALLET_ENV_VARS = [
  "APPLE_PASS_TYPE_IDENTIFIER",
  "APPLE_TEAM_IDENTIFIER",
  "APPLE_PASS_CERTIFICATE",
  "APPLE_PASS_CERTIFICATE_KEY",
  "APPLE_WWDR_CERTIFICATE",
] as const;

export function isAppleWalletConfigured(): boolean {
  return APPLE_WALLET_ENV_VARS.every((key) => Boolean(process.env[key]));
}

/**
 * Builds and signs a .pkpass buffer for the given card. Throws until the
 * environment variables above are configured and `passkit-generator` is
 * wired in — see the module doc comment for the integration plan.
 */
export async function generateApplePass(card: PublicWalletCard): Promise<Buffer> {
  void card;

  if (!isAppleWalletConfigured()) {
    throw new Error(
      "Apple Wallet n'est pas configuré. Ajoutez les certificats Apple Developer " +
        "(APPLE_PASS_TYPE_IDENTIFIER, APPLE_TEAM_IDENTIFIER, APPLE_PASS_CERTIFICATE, " +
        "APPLE_PASS_CERTIFICATE_KEY, APPLE_WWDR_CERTIFICATE) pour activer la génération de .pkpass."
    );
  }

  // Integration point: build + sign the pass here with `passkit-generator`
  // once the certificates above are configured.
  throw new Error("La génération de .pkpass n'est pas encore implémentée.");
}
